version: '3'

networks:
  app-network:
    driver: bridge

volumes:
  webdata:
    driver: local

services:
  web:
    build: ./src
    container_name: web
    volumes:
      - ./src:/var/www/
      - ./src/local.ini:/usr/local/etc/php/conf.d/local.ini
    working_dir: /var/www/
    networks:
      - app-network
    links:
      - mysql

  nginx:
    image: nginx:1.17
    container_name: web_server
    ports:
      - "80:80"
    working_dir: /var/www/
    depends_on:
      - web
    volumes:
      - ./src:/var/www/
      - ./nginx/server.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    links:
      - web

  mysql:
    image: mysql:5.6
    container_name: web_db
    volumes:
      - webdata:/var/lib/mysql
    ports:
      - "3306:3306"
    env_file:
      - ./src/.env
    networks:
      - app-network

  redis:
    image: redis
    container_name: web_redis
    ports:
      - "6379:6379"
