version: '3'

networks:
  app-network:
    driver: bridge

volumes:
  webdata:
    driver: local

services:
  web:
    build: ./web
    container_name: web
    volumes:
      - ./src/Server:/var/www
      - ./web/local.ini:/usr/local/etc/php/conf.d/local.ini
    working_dir: /var/www
    networks:
      - app-network


  composer:
    image: composer/composer
    command: composer install

  nginx:
    image: nginx:latest
    container_name: web_server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/server.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

  mysql:
    image: mysql:5.6
    container_name: web_db
    volumes:
      - webdata:/var/lib/mysql
    ports:
      - "3306:3306"
    env_file:
      - ./src/Server/.env
    networks:
      - app-network

  redis:
    image: redis
